@FieldsAreNonnullByDefault
@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.tobynguyen27.codebebelib.render.shader;

import javax.annotation.ParametersAreNonnullByDefault;
import net.covers1624.quack.annotation.FieldsAreNonnullByDefault;
import net.covers1624.quack.annotation.MethodsReturnNonnullByDefault;
